Models/AdoptiondbContext.cs
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace AdoptionMVC.Models;

public partial class AdoptiondbContext : DbContext
{
    public AdoptiondbContext()
    {
    }

    public AdoptiondbContext(DbContextOptions<AdoptiondbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Animal> Animals { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
        => optionsBuilder.UseSqlServer("Data Source=.\\sqlexpress;Initial Catalog=ADOPTIONDB; Integrated Security=SSPI;Encrypt=false;TrustServerCertificate=True;");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Animal>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Animals__3214EC07D221C38F");

            entity.Property(e => e.Breed).HasMaxLength(255);
            entity.Property(e => e.Description).HasMaxLength(255);
            entity.Property(e => e.Img).HasMaxLength(255);
            entity.Property(e => e.Name).HasMaxLength(255);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}

Models/Animal.cs
using System;
using System.Collections.Generic;

namespace AdoptionMVC.Models;

public partial class Animal
{
    public int Id { get; set; }

    public string? Img { get; set; }

    public string? Name { get; set; }

    public string? Description { get; set; }

    public string? Breed { get; set; }

    public int? Age { get; set; }
}

Models/ErrorViewModel.cs
namespace AdoptionMVC.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/AnimalController.cs
using AdoptionMVC.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace AdoptionMVC.Controllers
{
    public class AnimalController : Controller
    {
        AdoptiondbContext dbContext = new AdoptiondbContext();
        public IActionResult Index()
        {
            List<Animal> result = dbContext.Animals.ToList();
            return View(result);
        }
        public IActionResult ListByBreed(string breed)
        {
            List<Animal> result = dbContext.Animals.Where(p => p.Breed == breed).ToList();
            return View(result);
        }
        public IActionResult ConfirmAdoption(int id)
        {
            Animal result = dbContext.Animals.FirstOrDefault(p => p.Id == id);
            return View(result);
        }

        public IActionResult Delete(int id)
        {

            Animal result = dbContext.Animals.FirstOrDefault(p => p.Id == id);
            dbContext.Animals.Remove(result);
            dbContext.SaveChanges();
            return RedirectToAction("Index", "Home");

        }

    }
}

Controllers/HomeController.cs
using AdoptionMVC.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace AdoptionMVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }



        public IActionResult Privacy()
        {
            return View();
        }
        public IActionResult AddAPet()
        {

        return View(); 
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        AdoptiondbContext dbContext = new AdoptiondbContext();
        public IActionResult Index()
        {
            List<Animal> result = dbContext.Animals.ToList();
            return View(result);
        }
        public IActionResult ListByBreed(string breed)
        {
            List<Animal> result = dbContext.Animals.Where(p => p.Breed == breed).ToList();
            return View(result);

        }
        public IActionResult Result(Animal a)
        {
            dbContext.Animals.Add(a);
            dbContext.SaveChanges();
            return RedirectToAction("Index");
        }
        //public IActionResult AdoptAnAnimal(Animal a) {
    }

}

Views/Animal/ConfirmAdoption.cshtml
@model Animal

@{
    if (Model != null)
    {
        <h1>You're so close to your new best friend. Click adopt below to secure your pet.</h1>
        <div class="col-md-4 mb-4">
            <div class="container">
                <div class="card rounded">
                    <img src="@Model.Img" class="card-img-top img-thumbnail" style="object-fit:cover; width: 100%; height: auto" />
                    <h2 class="card-title">@Model.Name is @Model.Age</h2>
                    <p>@Model.Description</p>
                </div>
            </div>
        </div>

        <p>Our team will be in contact with you soon about your pet's new forever home. Once you click adopt, you will be redirected to the homepage</p>
        <form asp-controller="Animal" asp-action="Delete" method="post">
            <input type="hidden" name="id" value="@Model.Id" />
            <button type="submit" class="btn btn-success">Adopt</button>
        </form>
    }
    else
    {
        <h1>pet is no longer available</h1>
    }
}

Views/Animal/ListByBreed.cshtml
@model List<Animal>


<div class="container">
    <div class="row" data-masonry='{"percentPosition": true}'>
        @{
            @foreach (Animal a in Model)
            {
                <div class="col-md-4 mb-4">
                    <div class="card rounded">
                        <img src="@a.Img" class="card-img-top img-thumbnail" style="object-fit:cover; width: 100%; height: auto" />
                        <div class="card-body d-flex flex-column justify-content-center align-items-center">
                            <h2 class="card-title">@a.Name, @a.Age</h2>
                            <p class="card-text">@a.Description</p>
                            <form asp-controller="Animal" asp-action="ConfirmAdoption" method="get">
                                <input type="hidden" name="id" value="@a.Id" />
                                <button type="submit" class="btn btn-success">Adopt</button>
                            </form>
                        </div>
                    </div>
                </div>


            }

        }
    </div>

</div>   

Views/Home/AddAPet.cshtml
<form asp-method="post" asp-action="Result">
    <div class="mb-3">
        <label for="Img" class="form-label">Image</label>
        <input type="text" class="form-control" placeholder="Please enter a URL" name="Img" id="Img" required />
    </div>

    <div class="mb-3">
        <label for="Name" class="form-label">Name</label>
        <input type="text" class="form-control" placeholder="Jane" name="Name" id="Name" required />
    </div>

    <div class="mb-3">
        <label for="Description" class="form-label">Description</label>
        <input type="text" class="form-control"  placeholder="bundle of joy" name="Description" id="Description" required />
    </div>

    <div class="mb-3">
        <label for="Breed" class="form-label">Breed</label>
        <input type="text" class="form-control" placeholder="Cat,Dog,Etc" name="Breed" id="Breed" required />
    </div>
    <div class="mb-3">
        <label for="Age" class="form-label">Age</label>
        <input type="number" class="form-control" placeholder="0" name="Age" id="Age" required />
    </div>
    <div>
        <input type="submit" class="btn btn-light" />
    </div>
</form>

Views/Home/Index.cshtml
@model List<Animal>

<div class="text-center">
    <h1>
        Welcome To Kali's  Animal Shelter
    </h1>
    <h2>Find your new best friend!</h2>
    <form asp-controller="Animal" asp-action="ListByBreed" method="get">
        @{
            foreach (Animal a in Model.DistinctBy(a => a.Breed))

            {
                string iconClass = "";
                switch (a.Breed.ToLower())
                {
                    case "cat":
                        iconClass = "fas fa-cat";
                        break;
                    case "dog":
                        iconClass = "fas fa-dog";
                        break;
                    case "bird":
                        iconClass = "fa-solid fa-crow";
                        break;
                    default:
                        iconClass = "fas fa-paw";
                        break;
                }
                <button type="submit" class="btn-lg btn-light btn-square-md opacity-75" name="breed" value="@a.Breed">
                    <span style="display:flex; flex-direction:column; align-content:center">
                        <i class="@iconClass" style="font-size: 40px; font-display:block; margin-bottom: 10px"></i>
                        <span style="font-size: 16px">@a.Breed</span>
                    </span>
                </button>
            }

        }

    </form>
</div>
<img class="rounded-1 bg-opacity-75" style=" width: 100%; height: 405px; object-fit: cover;" src="https://images.unsplash.com/photo-1570824104453-508955ab713e?q=80&w=1911&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D" />

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
   
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AdoptionMVC</title>
    <script src="https://kit.fontawesome.com/7499fc3570.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AdoptionMVC.styles.css" asp-append-version="true" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/masonry-layout@4.2.2/dist/masonry.pkgd.min.js" integrity="sha384-GNFwBvfVxBkLMJpYMOABq3c+d3KnQxudP/mGPkzpZSTYykLBNsZEnG2D9G/X/+7D" crossorigin="anonymous" async></script>
   
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light  border-bottom box-shadow mb-3 nav">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Placing Paws and Claws</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="AddAPet">Add A Pet</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - AdoptionMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>